name: Adobe Patch Updates

on:
  schedule:
    - cron: '15 */7 * * *'  # Run every 7 hours, offset by 15 minutes from Cisco
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-adobe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Create vendor directory
        run: mkdir -p data/vendors

      - name: Fetch Adobe patches
        run: node scripts/vendors/adobe.js

      - name: Update combined patches file
        run: node scripts/fetch-patches.js

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/vendors/adobe.json data/patches.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Adobe patch data [skip ci]" && git push)

      - name: Deploy to GitHub Pages
        if: success()
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
